---
abstract: 'Minimal-configuration, read-only LDAP server'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  IO::Pipe: 0
  Net::LDAP: 0
  Proc::Fork: 0
  Test::More: 0.88
  Test::UseAllModules: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-LDAP-SimpleServer
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec: 0
  Net::LDAP::LDIF: 0
  Net::LDAP::Server: 0
  Net::LDAP::Util: 0
  Net::Server: 0
  Scalar::Util: 0
  UNIVERSAL::isa: 0
  common::sense: 0
  constant: 0
  diagnostics: 0
  fields: 0
resources:
  homepage: https://github.com/russoz/Net-LDAP-SimpleServer
  repository: https://github.com/russoz/Net-LDAP-SimpleServer
version: 0.0.13
